name: CI4CI
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - pip>=22.1.2
  - numpy>=1.23.1
  - pandas>=1.4.2
  - scipy>=1.8.1
  - rdkit>=2022.03.3
  - tqdm>=4.64.0
  - scikit-learn>=1.0.1
  - pytorch>=1.11
  - cudatoolkit>=11.3
  - chemprop
  - umap-learn
  - pywaffle
  - matplotlib>=3.4.3
  - regex  
  - scikit-image
  - statsmodels
